name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup on python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        dvc repro
        


